# Site settings
title: Ecostars ESG AI
email: tech@ecostars.org
featured-img: /img/ecostars-logo.png

# Build settings
markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
